# Generated by Django 5.2.13 on 2026-04-18 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=3)),
                ('codigo_iso', models.CharField(max_length=2)),
                ('bandera_url', models.URLField(blank=True, default='')),
                ('confederacion', models.CharField(choices=[('UEFA', 'UEFA - Europa'), ('CONMEBOL', 'CONMEBOL - Sudamérica'), ('CONCACAF', 'CONCACAF - Norte/Centro América y Caribe'), ('CAF', 'CAF - África'), ('AFC', 'AFC - Asia'), ('OFC', 'OFC - Oceanía')], max_length=20)),
                ('ranking_fifa', models.IntegerField(default=0)),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['ranking_fifa'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(choices=[('grupos', 'Fase de Grupos'), ('ronda32', 'Ronda de 32'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinales', 'Semifinales'), ('tercer_puesto', 'Tercer Puesto'), ('final', 'Final')], unique=True)),
                ('orden', models.IntegerField()),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('bloqueada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H'), ('I', 'Grupo I'), ('J', 'Grupo J'), ('K', 'Grupo K'), ('L', 'Grupo L')], max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupo')),
            ],
            options={
                'ordering': ['posicion'],
                'unique_together': {('grupo', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='equipos',
            field=models.ManyToManyField(related_name='grupos', through='core.GrupoEquipo', to='core.equipo'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('posicion', models.CharField(blank=True, choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('foto_url', models.URLField(blank=True, default='')),
                ('numero_camiseta', models.IntegerField(blank=True, null=True)),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='core.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['equipo', 'posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField(default=1)),
                ('fecha_hora', models.DateTimeField()),
                ('sede', models.CharField(blank=True, default='', max_length=100)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='programado', max_length=20)),
                ('resultado_cargado', models.BooleanField(default=False)),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='core.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='core.equipo')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='core.fase')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='core.grupo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PronosticoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_especiales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_asistente', to='core.jugador')),
                ('campeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_campeon', to='core.equipo')),
                ('cuarto_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_cuarto', to='core.equipo')),
                ('goleador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_goleador', to='core.jugador')),
                ('subcampeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_subcampeon', to='core.equipo')),
                ('tercer_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_tercer', to='core.equipo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pronostico_torneo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pronóstico de Torneo',
                'verbose_name_plural': 'Pronósticos de Torneo',
            },
        ),
        migrations.CreateModel(
            name='PronosticoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local_pred', models.IntegerField()),
                ('goles_visitante_pred', models.IntegerField()),
                ('puntos_ganados', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='core.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos_partido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pronóstico de Partido',
                'verbose_name_plural': 'Pronósticos de Partidos',
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
