# Generated by Django 4.2.28 on 2026-05-11 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronosticotorneo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pronosticotorneo',
            name='asistente_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pronosticotorneo',
            name='goleador_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quinielas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiniela',
                'verbose_name_plural': 'Quinielas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pronosticopartido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pronosticopartido',
            name='quiniela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos_partido', to='core.quiniela'),
        ),
        migrations.AddField(
            model_name='pronosticotorneo',
            name='quiniela',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pronostico_torneo', to='core.quiniela'),
        ),
        migrations.AlterUniqueTogether(
            name='pronosticopartido',
            unique_together={('quiniela', 'partido')},
        ),
        migrations.RemoveField(
            model_name='pronosticopartido',
            name='usuario',
        ),
    ]
