# Generated by Django 4.2.28 on 2026-05-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pronosticotorneo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador (No participa)'), ('pendiente', 'Pendiente de Validación'), ('pagada', 'Pagada (Participando)')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('VES', 'Bolívares (Bs.)'), ('USD', 'Dólares ($)')], max_length=3)),
                ('referencia', models.CharField(max_length=100)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('notas_admin', models.TextField(blank=True, default='')),
                ('quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.quiniela')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
