# Generated by Django 4.2.28 on 2026-05-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiniela_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiniela',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador (No participa)'), ('pendiente', 'Pendiente de Validación'), ('pagada', 'Pagada (Participando)'), ('rechazado', 'Pago Rechazado')], default='borrador', max_length=20),
        ),
    ]
